// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get homeLink => 'Home';

  @override
  String get pricingLink => 'Pricing';

  @override
  String get testimonialsLink => 'Testimonials';

  @override
  String get aboutUsLink => 'About Us';

  @override
  String get contactLink => 'Contact';

  @override
  String get registerButton => 'Register Now';

  @override
  String get loginButton => 'Log In';

  @override
  String get heroTitle => 'Making your workforce ';

  @override
  String get smarterWord => 'smarter';

  @override
  String get workforceWord => ' and faster.';

  @override
  String get landingDescription =>
      'AI-powered testing platform that helps you manage your employees, create tests, and analyze results efficiently.';

  @override
  String get landingHeroTitle => 'Test AI literacy. Document evidence.';

  @override
  String get landingHeroDesc =>
      'A structured entry point for companies that want to document their use of AI internally in a traceable, verifiable and centrally organized manner.';

  @override
  String get landingFeaturesSubtitle => 'Enterprise-Grade Assessment';

  @override
  String get landingFeaturesTitle =>
      'Built for security, scalability, and strict data isolation.';

  @override
  String get landingFeature1Title => 'Magic Link Access';

  @override
  String get landingFeature1Desc =>
      'Employees take tests securely via single-use, expiring magic links. Zero friction—no account creation or passwords required.';

  @override
  String get landingFeature2Title => 'Reporting & Certificates';

  @override
  String get landingFeature2Desc =>
      'Access comprehensive result dashboards, CSV exports, and automatically generated, professional PDF certificates upon passing.';

  @override
  String get landingFeature3Title => 'Strict Multi-Tenant Architecture';

  @override
  String get landingFeature3Desc =>
      'Total data isolation between organizations. Distinct roles for Owner Admins, Tenant Admins, and Employees ensure complete privacy.';

  @override
  String get landingHowItWorksSubtitle => 'Simple, Secure Workflow';

  @override
  String get landingStep1Title => 'Purchase Credits';

  @override
  String get landingStep1Desc =>
      'Acquire assessment credits securely through our transparent Stripe-integrated ledger.';

  @override
  String get landingStep2Title => 'Assign & Invite';

  @override
  String get landingStep2Desc =>
      'Assign immutable test versions and send automated, single-use magic links to employees.';

  @override
  String get landingStep3Title => 'Assess & Export';

  @override
  String get landingStep3Desc =>
      'Employees complete secure tests, while you instantly export CSV reports and PDF certificates.';

  @override
  String get landingDisclaimer =>
      'Legal Disclaimer: ai-test.eu is an assessment-only platform providing non-proctored evaluations. Results generated by this platform do not constitute official EU certification, legal advice, or legally binding credentials.';

  @override
  String get firstNameHint => 'Enter first name';

  @override
  String get lastNameHint => 'Enter last name';

  @override
  String get companyHint => 'Enter company name';

  @override
  String get addressHint => 'Enter company\'s address';

  @override
  String get loginTitle => 'Login to Dashboard';

  @override
  String get loginSubtitle => 'Fill the below form to login';

  @override
  String get emailLabel => 'Email';

  @override
  String get emailHint => 'Enter your email';

  @override
  String get passwordLabel => 'Password';

  @override
  String get passwordHint => 'Enter password';

  @override
  String get rememberMe => 'Remember me';

  @override
  String get forgotPassword => 'Forgot Password?';

  @override
  String get registerLink => 'Don\'t have an account?';

  @override
  String get registerNow => 'Register now';

  @override
  String get signupTitle => 'Create Account';

  @override
  String get signupSubtitle => 'Register for your account instantly!';

  @override
  String get firstName => 'First Name';

  @override
  String get lastName => 'Last Name';

  @override
  String get companyName => 'Company Name';

  @override
  String get country => 'Select Country';

  @override
  String get address => 'Address';

  @override
  String get haveAccount => 'Already have an account?';

  @override
  String get forgotPasswordTitle => 'Forgot Password';

  @override
  String get forgotPasswordSubtitle => 'Enter your email to receive an OTP';

  @override
  String get enterEmailHint => 'Enter your email';

  @override
  String get sendOtpButton => 'Send OTP';

  @override
  String get backToLogin => 'Back to Login';

  @override
  String get verifyOtpTitle => 'Verify OTP';

  @override
  String get verifyOtpSubtitle => 'Enter the 8-digit code sent to your email';

  @override
  String get resendOtpQuestion => 'Didn\'t receive code?';

  @override
  String get resendOtpButton => 'Resend OTP';

  @override
  String get verifyOtpButton => 'Verify OTP';

  @override
  String get resetPasswordTitle => 'Reset Password';

  @override
  String get resetPasswordSubtitle => 'Set your new password below';

  @override
  String get newPasswordLabel => 'New Password';

  @override
  String get newPasswordHint => 'Enter new password';

  @override
  String get confirmPasswordLabel => 'Confirm Password';

  @override
  String get confirmPasswordHint => 'Re-enter password';

  @override
  String get resetPasswordButton => 'Reset Password';

  @override
  String get termsTitle => 'Terms & Conditions';

  @override
  String get termsBody1 =>
      'By accessing and using this login page, you agree to be bound by these Terms and Conditions, along with any related policies referenced herein. This platform is intended solely for authorised users, and access is granted only for lawful purposes. You must ensure that all information provided during the login process is accurate, complete, and up to date. Any use of the system that is unlawful, fraudulent, or intended to harm the platform or its users is strictly prohibited.';

  @override
  String get termsBody2 =>
      'You are responsible for maintaining the confidentiality of your login credentials, including your username and password, and for all activities carried out under your account. You agree not to share your login details with any third party or allow unauthorised access. We shall not be liable for any loss or damage arising from your failure to protect your account information. If you suspect any unauthorised use of your account, you must notify us immediately.';

  @override
  String get termsBody3 =>
      'We reserve the right, at our sole discretion, to restrict, suspend, or terminate your access to the platform without prior notice if we believe you have breached these Terms and Conditions or engaged in conduct that may compromise system security, integrity, or functionality. We may also update or modify these terms at any time, and continued use of the login page constitutes acceptance of any such changes.';

  @override
  String get termsBody4 =>
      'Access to this platform is provided on an \"as is\" and \"as available\" basis. While we take reasonable steps to maintain system security and availability, we do not guarantee uninterrupted, error-free, or secure access at all times. By logging in, you acknowledge and accept our Privacy Policy and consent to the collection, storage, and processing of your personal data in accordance with applicable data protection laws and regulations in the United Kingdom.';

  @override
  String get dashboardOwner => 'Owner Dashboard';

  @override
  String get dashboardTenant => 'Tenant Dashboard';

  @override
  String get navDashboard => 'Dashboard';

  @override
  String get navTestMgmt => 'Test Management';

  @override
  String get navEmployees => 'Employees';

  @override
  String get navBilling => 'Billing';

  @override
  String get navBillingCredits => 'Billing & Credits';

  @override
  String get navResults => 'Results';

  @override
  String get statTotalTests => 'Total Tests';

  @override
  String get statTotalTenants => 'Total Tenants';

  @override
  String get statTotalEmployees => 'Total Employees';

  @override
  String get statPublished => 'Published Tests';

  @override
  String get statDraft => 'Draft Tests';

  @override
  String get statCreditsLeft => 'Credits Left';

  @override
  String get statMyEmployees => 'My Employees';

  @override
  String get statTestsTaken => 'Tests Taken';

  @override
  String get statPlatformPassRate => 'Platform Pass Rate';

  @override
  String get statPurchasedTests => 'Purchased Tests';

  @override
  String get statPendingAssignments => 'Pending Assignments';

  @override
  String get statCompletedTests => 'Completed Tests';

  @override
  String get statPassRate => 'Pass Rate';

  @override
  String get statTopDepartment => 'Top Department';

  @override
  String get testCreateNew => 'Create New Test';

  @override
  String get testFilterAll => 'All Tests';

  @override
  String get testFilterPublished => 'Published';

  @override
  String get testFilterDraft => 'Draft';

  @override
  String get testCredits => 'Credits';

  @override
  String get testVersion => 'Version';

  @override
  String get testCreatedBy => 'Created By';

  @override
  String get testCreatedAt => 'Created At';

  @override
  String get testStatus => 'Status';

  @override
  String get labelPublished => 'Published';

  @override
  String get labelDraft => 'Draft';

  @override
  String get labelFree => 'Free';

  @override
  String get labelFrom => 'From';

  @override
  String get labelVersion => 'Version';

  @override
  String get labelCreatedAt => 'Created At';

  @override
  String get labelCategoryColon => 'Category:';

  @override
  String get labelCategory => 'Category';

  @override
  String get justNow => 'Just Now';

  @override
  String get categoryGeneral => 'General';

  @override
  String get labelNumberOfSeats => 'Number of Seats';

  @override
  String get labelCreditsPerSeat => 'Credits Per Seat';

  @override
  String get labelTotal => 'Total';

  @override
  String get buttonAddToCart => 'Add to Cart';

  @override
  String get snackAddedToCart => 'Added to cart successfully';

  @override
  String get buttonBuyNow => 'Buy Now';

  @override
  String get billingCredits => 'Credits';

  @override
  String get billingBuy => 'Buy Credits';

  @override
  String get billingHistory => 'Billing history';

  @override
  String get billingDate => 'Date';

  @override
  String get billingDocument => 'Document';

  @override
  String get billingTotal => 'Total';

  @override
  String get billingAmount => 'Amount';

  @override
  String get billingStripeId => 'Stripe ID';

  @override
  String get billingReceipt => 'Receipt';

  @override
  String get billingCreditsPerSeat => 'Credits Per Seat';

  @override
  String get billingSeats => 'Seats';

  @override
  String get billingTestName => 'Test Name';

  @override
  String get billingVersion => 'Version';

  @override
  String get billingSeatsPurchased => 'Seats Purchased';

  @override
  String get billingTotalCredits => 'Total Credits';

  @override
  String get billingChoosePackage => 'Choose Package';

  @override
  String get billingSelectPackageSubtitle =>
      'Select the package that best fits your needs';

  @override
  String get tabBilling => 'Billing';

  @override
  String get tabPurchaseHistory => 'Purchase History';

  @override
  String get tabAvailableTests => 'Available Tests';

  @override
  String get tabPurchasedTestsLabel => 'Purchased Tests';

  @override
  String get hintSearch => 'Search...';

  @override
  String get hintEnterVat => 'Enter VAT number';

  @override
  String get hintSelectCountry => 'Select Country';

  @override
  String get hintSelectCategory => 'Select Category';

  @override
  String get labelAvailableCredits => 'Available Credits';

  @override
  String get labelCreditsLowercase => 'Credits';

  @override
  String get buttonBuyCredits => 'Buy Credits';

  @override
  String get filterAllTransactions => 'All Transactions';

  @override
  String get filterToday => 'Today';

  @override
  String get filterLast7Days => 'Last 7 Days';

  @override
  String get filterLast14Days => 'Last 14 Days';

  @override
  String get filterLast30Days => 'Last 30 Days';

  @override
  String get filterAllTests => 'All Tests';

  @override
  String get filterPublished => 'Published';

  @override
  String get filterDraft => 'Draft';

  @override
  String get buttonCreateNewTest => 'Create New Test';

  @override
  String get emptyNoTests => 'No tests available';

  @override
  String get emptyNoMatchingTests => 'No matching tests found';

  @override
  String get emptyNoPurchaseHistory => 'No purchase history';

  @override
  String get emptyNoPurchaseHistorySubtitle =>
      'You haven\'t made any purchases yet';

  @override
  String get buttonAssignEmployees => 'Assign Employees';

  @override
  String get buttonSelectSeats => 'Select Seats';

  @override
  String get resultsStatus => 'Status';

  @override
  String get resultsColEmployeeName => 'Employee Name';

  @override
  String get resultsColTestName => 'Test Name';

  @override
  String get resultsColVersion => 'Version';

  @override
  String get resultsColAttempt => 'Attempt';

  @override
  String get resultsColScore => 'Score';

  @override
  String get resultsColDate => 'Date';

  @override
  String get resultsColStatus => 'Status';

  @override
  String resultsCsvSaved(String path) {
    return 'CSV saved to $path';
  }

  @override
  String get resultsCertDownloaded => 'Certificate downloaded successfully';

  @override
  String resultsCertError(String error) {
    return 'Error downloading certificate: $error';
  }

  @override
  String get resultsNoPassedSelected => 'No passed tests selected';

  @override
  String resultsMultiCertDownloaded(int count) {
    return '$count Certificates downloaded successfully';
  }

  @override
  String get resultsSingleCertDownloaded =>
      'Certificate downloaded successfully';

  @override
  String get resultsNoResults => 'No results found';

  @override
  String get resultsSearchHint => 'Search results...';

  @override
  String get resultsGroupBy => 'Group By';

  @override
  String get resultsAll => 'All';

  @override
  String get resultsPass => 'Passed';

  @override
  String get resultsFail => 'Failed';

  @override
  String get resultsExportCsv => 'Export CSV';

  @override
  String get resultsGetCertificate => 'Get Certificate';

  @override
  String get empResultsPass => 'Pass';

  @override
  String get empResultsNotPassed => 'Not Passed';

  @override
  String get empResultsWellDone => 'Well Done!';

  @override
  String get empResultsComplete => 'Assessment Complete';

  @override
  String get empResultsScore => 'Score';

  @override
  String get empResultsCorrectAnswers => 'Correct Answers';

  @override
  String get empResultsTimeTaken => 'Time Taken';

  @override
  String get empResultsShareMessage => 'Share Results';

  @override
  String get empResultsExitPortal => 'Exit Portal';

  @override
  String get creditsLabel => 'Credits';

  @override
  String get profileButton => 'Profile';

  @override
  String get logoutButton => 'Logout';

  @override
  String get labelGroupBy => 'Group By';

  @override
  String get labelSortBy => 'Sort By';

  @override
  String get credits => 'Credits';

  @override
  String get labelId => 'ID';

  @override
  String get labelView => 'View';

  @override
  String get labelPopular => 'Popular';

  @override
  String get labelUsd => 'USD';

  @override
  String get testRunnerAssessmentComplete => 'Assessment Complete';

  @override
  String get testRunnerThankYou => 'Thank You';

  @override
  String get testRunnerViewResults => 'View Results';

  @override
  String get testRunnerReadyToSubmit => 'Ready to Submit?';

  @override
  String get testRunnerAnsweredQuestions => 'Questions Answered';

  @override
  String get testRunnerFlaggedForReview => 'Flagged for Review';

  @override
  String testRunnerUnansweredWarning(int count) {
    return 'You have $count unanswered question(s). Please review before submitting.';
  }

  @override
  String get testRunnerSubmitAssessment => 'Submit Assessment';

  @override
  String get testRunnerReturnToAssessment => 'Return to Assessment';

  @override
  String get testRunnerTestPublished => 'Test Published';

  @override
  String get testRunnerTestSubmitted => 'Test Submitted';

  @override
  String testRunnerLiveMessage(String testName) {
    return '$testName is live now';
  }

  @override
  String testRunnerSubmissionReceived(String testName) {
    return 'Your submission for $testName has been received';
  }

  @override
  String get testRunnerBackToTests => 'Back to Tests';

  @override
  String get testRunnerReturnToHome => 'Return to Home';

  @override
  String testRunnerSectionNum(int num) {
    return 'Section $num';
  }

  @override
  String testRunnerSectionTitle(int num, String title) {
    return 'Section $num: $title';
  }

  @override
  String testRunnerQuestionCount(int count) {
    return 'Question $count';
  }

  @override
  String get labelFlagged => 'Flagged';

  @override
  String get labelFlagForReview => 'Flag for Review';

  @override
  String get buttonBack => 'Back';

  @override
  String get buttonPublish => 'Publish';

  @override
  String get buttonSubmit => 'Submit';

  @override
  String get buttonNext => 'Next';

  @override
  String get buttonSelect => 'Select';

  @override
  String get tableSelectAll => 'Select All';

  @override
  String get tableNoItems => 'No items to display';

  @override
  String get profileUpdateSuccess => 'Profile updated successfully';

  @override
  String get profileUpdateFailed => 'Failed to update profile';

  @override
  String get profileTitle => 'Profile';

  @override
  String get editProfile => 'Edit Profile';

  @override
  String get nameLabel => 'Name';

  @override
  String get companyNameLabel => 'Company Name';

  @override
  String get countryLabel => 'Country';

  @override
  String get categoryLabel => 'Category';

  @override
  String get vatLabel => 'VAT';

  @override
  String get addressLabel => 'Address';

  @override
  String get bookkeepingEmailLabel => 'Bookkeeping Email';

  @override
  String get enterEmailPrompt => 'Enter email';

  @override
  String get firstNameLabel => 'First Name';

  @override
  String get lastNameLabel => 'Last Name';

  @override
  String get selectCategoryHint => 'Select Category';

  @override
  String get vatNumberHint => 'Enter VAT number';

  @override
  String get languageLabel => 'Language';

  @override
  String get englishLanguage => 'English';

  @override
  String get germanLanguage => 'German';

  @override
  String get bookkeepingEmailCheckboxLabel =>
      'Send invoices to bookkeeping email';

  @override
  String get forBookkeepingEmailLabel => 'Bookkeeping Email';

  @override
  String get enterBookkeepingEmailHint => 'Enter bookkeeping email';

  @override
  String get cancelButton => 'Cancel';

  @override
  String get saveChangesButton => 'Save Changes';

  @override
  String get errorPasswordRequired => 'Password is required';

  @override
  String get errorNewPasswordRequired => 'New password is required';

  @override
  String get errorConfirmPasswordRequired => 'Please confirm your password';

  @override
  String get errorFirstNameRequired => 'First name is required';

  @override
  String get errorLastNameRequired => 'Last name is required';

  @override
  String get errorEmailRequired => 'Email is required';

  @override
  String get loadingLogin => 'Logging in...';

  @override
  String get loadingResetLink => 'Sending reset link...';

  @override
  String get loadingVerifyOtp => 'Verifying OTP...';

  @override
  String get loadingResendOtp => 'Resending OTP...';

  @override
  String get loadingResettingPassword => 'Resetting password...';

  @override
  String get snackEnterValidEmail => 'Please enter a valid email address';

  @override
  String get snackWeakPassword =>
      'Password must be at least 8 characters with uppercase, lowercase, number, and special character';

  @override
  String get snackAccountCreated =>
      'Account created successfully! Please check your email to verify your account.';

  @override
  String get snackRegistrationFailed => 'Registration failed';

  @override
  String get snackEmailTaken => 'This email is already registered';

  @override
  String get snackInvalidEmailFormat => 'Invalid email format';

  @override
  String get snackPasswordRequirements => 'Password does not meet requirements';

  @override
  String get snackSignupSuccess => 'Signup successful';

  @override
  String get snackFillAllFields => 'Please fill all fields';

  @override
  String get snackLoginFailed => 'Login failed';

  @override
  String get snackInvalidCreds => 'Invalid email or password';

  @override
  String get snackVerifyEmail => 'Please verify your email first';

  @override
  String get snackNetworkError => 'Network error. Please check your connection';

  @override
  String get snackEnterEmail => 'Please enter your email';

  @override
  String get snackOtpSent => 'Verification code sent to your email';

  @override
  String get snackSendOtpFailed => 'Failed to send reset email';

  @override
  String get snackEmailNotFound => 'Email not found';

  @override
  String get snackEnterCompleteOtp => 'Please enter complete OTP';

  @override
  String get snackOtpVerified => 'OTP verified successfully';

  @override
  String get snackInvalidOtp => 'Invalid or expired OTP';

  @override
  String get snackEmailMissing => 'Email is missing. Please go back.';

  @override
  String get snackOtpResent => 'Verification code resent to your email';

  @override
  String get snackResendOtpFailed => 'Failed to resend OTP';

  @override
  String get snackPasswordMismatch => 'Passwords do not match';

  @override
  String get snackPasswordTooShort => 'Password must be at least 6 characters';

  @override
  String get snackPasswordResetSuccess => 'Password reset successfully';

  @override
  String get snackPasswordResetFailed => 'Failed to reset password';

  @override
  String get empInvite => 'Invite Employee';

  @override
  String get empAdd => 'Add Employees';

  @override
  String get empUploadCsv => 'Upload CSV';

  @override
  String get vatOptional => 'VAT (Optional)';

  @override
  String get landingNavProduct => 'product';

  @override
  String get landingNavWorkflow => 'Sequence';

  @override
  String get landingNavEvidence => 'Evidence';

  @override
  String get landingNavPricing => 'Prices';

  @override
  String get landingNavStart => 'Start Now';

  @override
  String get landingHeroEyebrow => 'AI Compliance Test from Rulefox';

  @override
  String get landingHeroCtaPrimary => 'Start AI Compliance Test';

  @override
  String get landingHeroCtaSecondary => 'View example proof';

  @override
  String get landingBenefit1Title => 'Invite employees';

  @override
  String get landingBenefit1Desc =>
      'Import via CSV or manually and assign tests in a structured manner.';

  @override
  String get landingBenefit2Title => 'Documenting AI Literacy';

  @override
  String get landingBenefit2Desc =>
      'Track progress, completion rates, and status centrally.';

  @override
  String get landingBenefit3Title => 'Export evidence';

  @override
  String get landingBenefit3Desc =>
      'Prepare reports for internal documentation, management, or audits.';

  @override
  String get landingFooterTagline =>
      'AI Compliance & Literacy Platform for Enterprise';

  @override
  String get footerImpressum => 'Impressum';

  @override
  String get footerDatenschutz => 'Privacy Policy';

  @override
  String get footerKontakt => 'Contact';

  @override
  String get navOverview => 'Overview';

  @override
  String get navTests => 'Tests';

  @override
  String get navEvidence => 'Evidence';

  @override
  String get navInvoice => 'Invoice';

  @override
  String get navSettings => 'Settings';

  @override
  String get dashboardTenantTitle => 'AI Compliance Dashboard';

  @override
  String get dashboardTenantSubtitle =>
      'Document AI literacy, test status and evidence centrally in Rulefox.';

  @override
  String get dashboardBannerTitle => 'AI Compliance in Focus';

  @override
  String get dashboardBannerDesc =>
      'Easily and clearly keep track of your employees\' test status, evidence, and AI literacy.';

  @override
  String get dashboardBannerCta => 'More about the EU AI Act';

  @override
  String get statEmployeesRecorded => 'Employees recorded';

  @override
  String get statEmployeesNoData => 'No employees added yet';

  @override
  String get statTestsAssigned => 'assigned tests';

  @override
  String get statTestsNoData => 'No tests assigned yet';

  @override
  String get statCompleted => 'Completed';

  @override
  String get statCompletionRate => 'Completion rate';

  @override
  String get statEvidenceAvailable => 'Evidence available';

  @override
  String get statEvidenceNoData => 'No evidence available yet';

  @override
  String get nextStepsTitle => 'Next Steps';

  @override
  String get step1Title => 'Complete company data';

  @override
  String get step1Desc => 'Add to your company information';

  @override
  String get step1Btn => 'Start';

  @override
  String get step2Title => 'Employees import';

  @override
  String get step2Desc => 'Upload your employees or add them manually.';

  @override
  String get step2Btn => 'Import';

  @override
  String get step3Title => 'Assign compliance test';

  @override
  String get step3Desc => 'Assign the AI compliance test to your employees';

  @override
  String get step3Btn => 'Assign test';

  @override
  String get step4Title => 'Export evidence';

  @override
  String get step4Desc => 'Export evidence for internal or external audits';

  @override
  String get step4Btn => 'Evidence';

  @override
  String get currentAllocationsTitle => 'Current allocations';

  @override
  String get showAll => 'Show all';

  @override
  String get noTestsAssigned => 'No tests assigned yet';

  @override
  String get noTestsAssignedDesc =>
      'Once you assign tests, you will see the status and progress of your employees here.';

  @override
  String get inviteEmployees => 'Invite employees';

  @override
  String get titleLanding => 'RuleFox – AI Compliance for Enterprise';

  @override
  String get titleLogin => 'Login · RuleFox';

  @override
  String get titleSignup => 'Registration · RuleFox';

  @override
  String get titleDashboard => 'AI Compliance Dashboard · RuleFox';

  @override
  String get titleAssessmentComplete => 'Assessment completed · RuleFox';

  @override
  String get titleOwnerDashboard => 'Owner Dashboard · RuleFox';

  @override
  String get titleOwnerTestManagement => 'Test Management · RuleFox';

  @override
  String get titleOwnerNewTest => 'New test · RuleFox';

  @override
  String get titleTenantDashboard => 'AI Compliance Dashboard · RuleFox';

  @override
  String get titleTenantAvailableTests => 'Available tests · RuleFox';

  @override
  String get titleTenantTestQuota => 'Test quota · RuleFox';

  @override
  String get titleAssignEmployees => 'Assign employees · RuleFox';

  @override
  String get titleEmployees => 'Employees · RuleFox';

  @override
  String get titleBilling => 'Billing · RuleFox';

  @override
  String get titlePurchaseHistory => 'Purchase history · RuleFox';

  @override
  String get titleCheckout => 'Checkout · RuleFox';

  @override
  String get titleAssessmentReady => 'Assessment ready · RuleFox';

  @override
  String get titleTestDetail => 'AI Compliance Test · RuleFox';

  @override
  String get titleAssessmentQuestions => 'AI Compliance Test · RuleFox';

  @override
  String get titleResults => 'Results · RuleFox';

  @override
  String get landingHeroStatEmployees => 'Employees';

  @override
  String get landingHeroStatCompleted => 'Completed';

  @override
  String get landingHeroBannerTitle => 'AI Compliance at a glance';

  @override
  String get landingHeroBannerDesc =>
      'Manage test status, employees and evidence centrally.';

  @override
  String get landingHeroDashboardTitle => 'AI Compliance Dashboard';

  @override
  String navQuota(Object count) {
    return 'Quota: $count tests';
  }

  @override
  String get navFooterTagline => 'Compliance that is verifiable.';

  @override
  String get navFooterLogoText => 'RULEFOX';
}
