// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get homeLink => 'Home';

  @override
  String get pricingLink => 'Pricing';

  @override
  String get testimonialsLink => 'Testimonials';

  @override
  String get aboutUsLink => 'About Us';

  @override
  String get contactLink => 'Contact';

  @override
  String get registerButton => 'Register Now';

  @override
  String get loginButton => 'Log In';

  @override
  String get heroTitle => 'Making your workforce ';

  @override
  String get smarterWord => 'smarter';

  @override
  String get workforceWord => ' and faster.';

  @override
  String get landingDescription =>
      'AI-powered testing platform that helps you manage your employees, create tests, and analyze results efficiently.';

  @override
  String get landingHeroTitle => 'Test AI literacy. Document evidence.';

  @override
  String get landingHeroDesc =>
      'A structured entry point for companies that want to document their use of AI internally in a traceable, verifiable and centrally organized manner.';

  @override
  String get landingFeaturesSubtitle => 'Enterprise-Grade Assessment';

  @override
  String get landingFeaturesTitle =>
      'Built for security, scalability, and strict data isolation.';

  @override
  String get landingFeature1Title => 'Magic Link Access';

  @override
  String get landingFeature1Desc =>
      'Employees take tests securely via single-use, expiring magic links. Zero friction—no account creation or passwords required.';

  @override
  String get landingFeature2Title => 'Reporting & Certificates';

  @override
  String get landingFeature2Desc =>
      'Access comprehensive result dashboards, CSV exports, and automatically generated, professional PDF certificates upon passing.';

  @override
  String get landingFeature3Title => 'Strict Multi-Tenant Architecture';

  @override
  String get landingFeature3Desc =>
      'Total data isolation between organizations. Distinct roles for Owner Admins, Tenant Admins, and Employees ensure complete privacy.';

  @override
  String get landingHowItWorksSubtitle => 'Simple, Secure Workflow';

  @override
  String get landingStep1Title => 'Purchase Credits';

  @override
  String get landingStep1Desc =>
      'Acquire assessment credits securely through our transparent Stripe-integrated ledger.';

  @override
  String get landingStep2Title => 'Assign & Invite';

  @override
  String get landingStep2Desc =>
      'Assign immutable test versions and send automated, single-use magic links to employees.';

  @override
  String get landingStep3Title => 'Assess & Export';

  @override
  String get landingStep3Desc =>
      'Employees complete secure tests, while you instantly export CSV reports and PDF certificates.';

  @override
  String get landingDisclaimer =>
      'Legal Disclaimer: ai-test.eu is an assessment-only platform providing non-proctored evaluations. Results generated by this platform do not constitute official EU certification, legal advice, or legally binding credentials.';

  @override
  String get firstNameHint => 'Enter first name';

  @override
  String get lastNameHint => 'Enter last name';

  @override
  String get companyHint => 'Enter company name';

  @override
  String get addressHint => 'Enter company\'s address';

  @override
  String get loginTitle => 'Login to Dashboard';

  @override
  String get loginSubtitle => 'Fill the below form to login';

  @override
  String get emailLabel => 'Email';

  @override
  String get emailHint => 'Enter your email';

  @override
  String get passwordLabel => 'Password';

  @override
  String get passwordHint => 'Enter password';

  @override
  String get rememberMe => 'Remember me';

  @override
  String get forgotPassword => 'Forgot Password?';

  @override
  String get registerLink => 'Don\'t have an account?';

  @override
  String get registerNow => 'Register now';

  @override
  String get signupTitle => 'Create Account';

  @override
  String get signupSubtitle => 'Register for your account instantly!';

  @override
  String get firstName => 'First Name';

  @override
  String get lastName => 'Last Name';

  @override
  String get companyName => 'Company Name';

  @override
  String get country => 'Select Country';

  @override
  String get address => 'Address';

  @override
  String get haveAccount => 'Already have an account?';

  @override
  String get forgotPasswordTitle => 'Forgot Password';

  @override
  String get forgotPasswordSubtitle => 'Enter your email to receive an OTP';

  @override
  String get enterEmailHint => 'Enter your email';

  @override
  String get sendOtpButton => 'Send OTP';

  @override
  String get backToLogin => 'Back to Login';

  @override
  String get verifyOtpTitle => 'Verify OTP';

  @override
  String get verifyOtpSubtitle => 'Enter the 8-digit code sent to your email';

  @override
  String get resendOtpQuestion => 'Didn\'t receive code?';

  @override
  String get resendOtpButton => 'Resend OTP';

  @override
  String get verifyOtpButton => 'Verify OTP';

  @override
  String get resetPasswordTitle => 'Reset Password';

  @override
  String get resetPasswordSubtitle => 'Set your new password below';

  @override
  String get newPasswordLabel => 'New Password';

  @override
  String get newPasswordHint => 'Enter new password';

  @override
  String get confirmPasswordLabel => 'Confirm Password';

  @override
  String get confirmPasswordHint => 'Re-enter password';

  @override
  String get resetPasswordButton => 'Reset Password';

  @override
  String get termsTitle => 'Terms & Conditions';

  @override
  String get termsBody1 =>
      'By accessing and using this login page, you agree to be bound by these Terms and Conditions, along with any related policies referenced herein. This platform is intended solely for authorised users, and access is granted only for lawful purposes. You must ensure that all information provided during the login process is accurate, complete, and up to date. Any use of the system that is unlawful, fraudulent, or intended to harm the platform or its users is strictly prohibited.';

  @override
  String get termsBody2 =>
      'You are responsible for maintaining the confidentiality of your login credentials, including your username and password, and for all activities carried out under your account. You agree not to share your login details with any third party or allow unauthorised access. We shall not be liable for any loss or damage arising from your failure to protect your account information. If you suspect any unauthorised use of your account, you must notify us immediately.';

  @override
  String get termsBody3 =>
      'We reserve the right, at our sole discretion, to restrict, suspend, or terminate your access to the platform without prior notice if we believe you have breached these Terms and Conditions or engaged in conduct that may compromise system security, integrity, or functionality. We may also update or modify these terms at any time, and continued use of the login page constitutes acceptance of any such changes.';

  @override
  String get termsBody4 =>
      'Access to this platform is provided on an \"as is\" and \"as available\" basis. While we take reasonable steps to maintain system security and availability, we do not guarantee uninterrupted, error-free, or secure access at all times. By logging in, you acknowledge and accept our Privacy Policy and consent to the collection, storage, and processing of your personal data in accordance with applicable data protection laws and regulations in the United Kingdom.';

  @override
  String get dashboardOwner => 'Owner Dashboard';

  @override
  String get dashboardTenant => 'Tenant Dashboard';

  @override
  String get navDashboard => 'Dashboard';

  @override
  String get navTestMgmt => 'Test Management';

  @override
  String get navBilling => 'Billing';

  @override
  String get navBillingCredits => 'Billing & Credits';

  @override
  String get navResults => 'Results';

  @override
  String get statTotalTests => 'Total Tests';

  @override
  String get statTotalTenants => 'Total Tenants';

  @override
  String get statTotalEmployees => 'Total Employees';

  @override
  String get statPublished => 'Published Tests';

  @override
  String get statDraft => 'Draft Tests';

  @override
  String get statCreditsLeft => 'Credits Left';

  @override
  String get statMyEmployees => 'My Employees';

  @override
  String get statTestsTaken => 'Tests Taken';

  @override
  String get statPlatformPassRate => 'Platform Pass Rate';

  @override
  String get statPurchasedTests => 'Purchased Tests';

  @override
  String get statPendingAssignments => 'Pending Assignments';

  @override
  String get statCompletedTests => 'Completed Tests';

  @override
  String get statPassRate => 'Pass Rate';

  @override
  String get statTopDepartment => 'Top Department';

  @override
  String get testCreateNew => 'Create New Test';

  @override
  String get testFilterAll => 'All Tests';

  @override
  String get testFilterPublished => 'Published';

  @override
  String get testFilterDraft => 'Draft';

  @override
  String get testCredits => 'Credits';

  @override
  String get testVersion => 'Version';

  @override
  String get testCreatedBy => 'Created By';

  @override
  String get testCreatedAt => 'Created At';

  @override
  String get testStatus => 'Status';

  @override
  String get labelPublished => 'Published';

  @override
  String get labelDraft => 'Draft';

  @override
  String get labelFree => 'Free';

  @override
  String get labelFrom => 'From';

  @override
  String get labelVersion => 'Version';

  @override
  String get labelCreatedAt => 'Created At';

  @override
  String get labelCategoryColon => 'Category:';

  @override
  String get labelCategory => 'category';

  @override
  String get justNow => 'Just Now';

  @override
  String get categoryGeneral => 'General';

  @override
  String get labelNumberOfSeats => 'Number of Seats';

  @override
  String get labelCreditsPerSeat => 'Credits Per Seat';

  @override
  String get labelTotal => 'Total';

  @override
  String get buttonAddToCart => 'Add to Cart';

  @override
  String get snackAddedToCart => 'Added to cart successfully';

  @override
  String get buttonBuyNow => 'Buy Now';

  @override
  String get billingCredits => 'Credits';

  @override
  String get billingBuy => 'Buy Credits';

  @override
  String get billingHistory => 'Billing history';

  @override
  String get billingDate => 'Date';

  @override
  String get billingDocument => 'Document';

  @override
  String get billingTotal => 'Total';

  @override
  String get billingAmount => 'Amount';

  @override
  String get billingStripeId => 'Stripe ID';

  @override
  String get billingReceipt => 'Receipt';

  @override
  String get billingCreditsPerSeat => 'Credits Per Seat';

  @override
  String get billingSeats => 'Seats';

  @override
  String get billingTestName => 'Test Name';

  @override
  String get billingVersion => 'Version';

  @override
  String get billingSeatsPurchased => 'Seats Purchased';

  @override
  String get billingTotalCredits => 'Total Credits';

  @override
  String get billingChoosePackage => 'Choose Package';

  @override
  String get billingSelectPackageSubtitle =>
      'Select the package that best fits your needs';

  @override
  String get billingColumnDate => 'Date';

  @override
  String get billingColumnProduct => 'Product';

  @override
  String get billingColumnNumber => 'Number';

  @override
  String get billingColumnAmount => 'Amount';

  @override
  String get billingColumnStatus => 'Status';

  @override
  String get billingColumnInvoice => 'Invoice';

  @override
  String get tabBilling => 'Billing';

  @override
  String get tabPurchaseHistory => 'Purchase History';

  @override
  String get tabAvailableTests => 'Available Credits';

  @override
  String get tabPurchasedTestsLabel => 'Purchased Credits';

  @override
  String get hintSearch => 'Search...';

  @override
  String get hintEnterVat => 'Enter VAT number';

  @override
  String get hintSelectCountry => 'Select Country';

  @override
  String get hintSelectCategory => 'Select Category';

  @override
  String get labelNotAssigned => 'Not assigned';

  @override
  String get labelLinkSent => 'Link sent';

  @override
  String get labelTestExpired => 'Test expired';

  @override
  String get labelAvailableCredits => 'Available Credits';

  @override
  String get labelCreditsLowercase => 'Credits';

  @override
  String get buttonBuyCredits => 'Quota';

  @override
  String get filterAllTransactions => 'All Transactions';

  @override
  String get filterToday => 'Today';

  @override
  String get filterLast7Days => 'Last 7 Days';

  @override
  String get filterLast14Days => 'Last 14 Days';

  @override
  String get filterLast30Days => 'Last 30 Days';

  @override
  String get filterAllTests => 'All Tests';

  @override
  String get filterPublished => 'Published';

  @override
  String get filterDraft => 'Draft';

  @override
  String get buttonCreateNewTest => 'Create New Test';

  @override
  String get emptyNoTests => 'No tests available';

  @override
  String get emptyNoMatchingTests => 'No matching tests found';

  @override
  String get emptyNoPurchaseHistory => 'No purchase history';

  @override
  String get emptyNoPurchaseHistorySubtitle =>
      'You haven\'t made any purchases yet';

  @override
  String get buttonAssignEmployees => 'Assign Employees';

  @override
  String get buttonSelectSeats => 'Select Seats';

  @override
  String get resultsStatus => 'Status';

  @override
  String get resultsColEmployeeName => 'Employee Name';

  @override
  String get resultsColTestName => 'Test Name';

  @override
  String get resultsColVersion => 'Version';

  @override
  String get resultsColAttempt => 'Attempt';

  @override
  String get resultsColScore => 'Score';

  @override
  String get resultsColDate => 'Date';

  @override
  String get resultsColStatus => 'Status';

  @override
  String resultsCsvSaved(String path) {
    return 'CSV saved to $path';
  }

  @override
  String get resultsCertDownloaded => 'Certificate downloaded successfully';

  @override
  String resultsCertError(String error) {
    return 'Error downloading certificate: $error';
  }

  @override
  String get resultsNoPassedSelected => 'No passed tests selected';

  @override
  String resultsMultiCertDownloaded(int count) {
    return '$count Certificates downloaded successfully';
  }

  @override
  String get resultsSingleCertDownloaded =>
      'Certificate downloaded successfully';

  @override
  String get resultsNoResults => 'No results found';

  @override
  String get resultsSearchHint => 'Search employees';

  @override
  String get resultsGroupBy => 'Group By';

  @override
  String get resultsAll => 'All';

  @override
  String get resultsPass => 'Passed';

  @override
  String get resultsFail => 'Failed';

  @override
  String get resultsExportCsv => 'Export CSV';

  @override
  String get resultsGetCertificate => 'Get Certificate';

  @override
  String get empResultsPass => 'Pass';

  @override
  String get empResultsNotPassed => 'Not Passed';

  @override
  String get empResultsWellDone => 'Well Done!';

  @override
  String get empResultsComplete => 'Assessment Complete';

  @override
  String get empResultsScore => 'Score';

  @override
  String get empResultsCorrectAnswers => 'Correct Answers';

  @override
  String get empResultsTimeTaken => 'Time Taken';

  @override
  String get empResultsShareMessage => 'Share Results';

  @override
  String get empResultsExitPortal => 'Exit Portal';

  @override
  String get creditsLabel => 'Credits';

  @override
  String get profileButton => 'Profile';

  @override
  String get logoutButton => 'Logout';

  @override
  String get labelGroupBy => 'Group By';

  @override
  String get labelSortBy => 'Sort By';

  @override
  String get credits => 'Credits';

  @override
  String get labelId => 'ID';

  @override
  String get labelView => 'View';

  @override
  String get labelPopular => 'Popular';

  @override
  String get labelUsd => 'USD';

  @override
  String get testRunnerAssessmentComplete => 'Assessment Complete';

  @override
  String get testRunnerThankYou => 'Thank You';

  @override
  String get testRunnerViewResults => 'View Results';

  @override
  String get testRunnerReadyToSubmit => 'Ready to Submit?';

  @override
  String get testRunnerAnsweredQuestions => 'Questions Answered';

  @override
  String get testRunnerFlaggedForReview => 'Flagged for Review';

  @override
  String testRunnerUnansweredWarning(int count) {
    return 'You have $count unanswered question(s). Please review before submitting.';
  }

  @override
  String get testRunnerSubmitAssessment => 'Submit Assessment';

  @override
  String get testRunnerReturnToAssessment => 'Return to Assessment';

  @override
  String get assessmentMetricQuestions => 'Questions';

  @override
  String get assessmentMetricDuration => 'Duration';

  @override
  String get assessmentMetricLanguage => 'Language';

  @override
  String get assessmentMetricNoLimit => 'No Limit';

  @override
  String get assessmentStartTest => 'Start Test';

  @override
  String get assessmentResumeTest => 'Resume Test';

  @override
  String assessmentSectionQuestions(Object count) {
    return '$count questions';
  }

  @override
  String get assessmentTimedNotice => 'This is a timed assessment.';

  @override
  String get testRunnerTestPublished => 'Test Published';

  @override
  String get testRunnerTestSubmitted => 'Test Submitted';

  @override
  String testRunnerLiveMessage(String testName) {
    return '$testName is live now';
  }

  @override
  String testRunnerSubmissionReceived(String testName) {
    return 'Your submission for $testName has been received';
  }

  @override
  String get testRunnerBackToTests => 'Back to Tests';

  @override
  String get testRunnerReturnToHome => 'Return to Home';

  @override
  String testRunnerSectionNum(int num) {
    return 'Section $num';
  }

  @override
  String testRunnerSectionTitle(int num, String title) {
    return 'Section $num: $title';
  }

  @override
  String testRunnerQuestionCount(int count) {
    return 'Question $count';
  }

  @override
  String get labelFlagged => 'Flagged';

  @override
  String get labelFlagForReview => 'Flag for Review';

  @override
  String get buttonBack => 'Back';

  @override
  String get buttonPublish => 'Publish';

  @override
  String get buttonSubmit => 'Submit';

  @override
  String get buttonNext => 'Next';

  @override
  String get buttonSelect => 'Select';

  @override
  String get tableSelectAll => 'Select All';

  @override
  String get tableNoItems => 'No items to display';

  @override
  String get profileUpdateSuccess => 'Profile updated successfully';

  @override
  String get profileUpdateFailed => 'Failed to update profile';

  @override
  String get profileTitle => 'Profile';

  @override
  String get editProfile => 'Edit Profile';

  @override
  String get nameLabel => 'Name';

  @override
  String get companyNameLabel => 'Company Name';

  @override
  String get countryLabel => 'Country';

  @override
  String get categoryLabel => 'Category';

  @override
  String get vatLabel => 'VAT';

  @override
  String get addressLabel => 'Address';

  @override
  String get bookkeepingEmailLabel => 'Bookkeeping Email';

  @override
  String get enterEmailPrompt => 'Enter email';

  @override
  String get firstNameLabel => 'First Name';

  @override
  String get lastNameLabel => 'Last Name';

  @override
  String get selectCategoryHint => 'Select Category';

  @override
  String get vatNumberHint => 'Enter VAT number';

  @override
  String get languageLabel => 'Language';

  @override
  String get englishLanguage => 'English';

  @override
  String get germanLanguage => 'German';

  @override
  String get bookkeepingEmailCheckboxLabel =>
      'Send invoices to bookkeeping email';

  @override
  String get forBookkeepingEmailLabel => 'Bookkeeping Email';

  @override
  String get enterBookkeepingEmailHint => 'Enter bookkeeping email';

  @override
  String get cancelButton => 'Cancel';

  @override
  String get saveChangesButton => 'Save Changes';

  @override
  String get errorPasswordRequired => 'Password is required';

  @override
  String get errorNewPasswordRequired => 'New password is required';

  @override
  String get errorConfirmPasswordRequired => 'Please confirm your password';

  @override
  String get errorFirstNameRequired => 'First name is required';

  @override
  String get errorLastNameRequired => 'Last name is required';

  @override
  String get errorEmailRequired => 'Email is required';

  @override
  String get loadingLogin => 'Logging in...';

  @override
  String get loadingResetLink => 'Sending reset link...';

  @override
  String get loadingVerifyOtp => 'Verifying OTP...';

  @override
  String get loadingResendOtp => 'Resending OTP...';

  @override
  String get loadingResettingPassword => 'Resetting password...';

  @override
  String get snackEnterValidEmail => 'Please enter a valid email address';

  @override
  String get snackWeakPassword =>
      'Password must be at least 8 characters with uppercase, lowercase, number, and special character';

  @override
  String get snackAccountCreated =>
      'Account created successfully! Please check your email to verify your account.';

  @override
  String get snackRegistrationFailed => 'Registration failed';

  @override
  String get snackEmailTaken => 'This email is already registered';

  @override
  String get snackInvalidEmailFormat => 'Invalid email format';

  @override
  String get snackPasswordRequirements => 'Password does not meet requirements';

  @override
  String get snackSignupSuccess => 'Signup successful';

  @override
  String get snackFillAllFields => 'Please fill all fields';

  @override
  String get snackLoginFailed => 'Login failed';

  @override
  String get snackInvalidCreds => 'Invalid email or password';

  @override
  String get snackVerifyEmail => 'Please verify your email first';

  @override
  String get snackNetworkError => 'Network error. Please check your connection';

  @override
  String get snackEnterEmail => 'Please enter your email';

  @override
  String get snackOtpSent => 'Verification code sent to your email';

  @override
  String get snackSendOtpFailed => 'Failed to send reset email';

  @override
  String get snackEmailNotFound => 'Email not found';

  @override
  String get snackEnterCompleteOtp => 'Please enter complete OTP';

  @override
  String get snackOtpVerified => 'OTP verified successfully';

  @override
  String get snackInvalidOtp => 'Invalid or expired OTP';

  @override
  String get snackEmailMissing => 'Email is missing. Please go back.';

  @override
  String get snackOtpResent => 'Verification code resent to your email';

  @override
  String get snackResendOtpFailed => 'Failed to resend OTP';

  @override
  String get snackPasswordMismatch => 'Passwords do not match';

  @override
  String get snackPasswordTooShort => 'Password must be at least 6 characters';

  @override
  String get snackPasswordResetSuccess => 'Password reset successfully';

  @override
  String get snackPasswordResetFailed => 'Failed to reset password';

  @override
  String get empInvite => 'Invite Employee';

  @override
  String get empAdd => 'Add Employees';

  @override
  String get empUploadCsv => 'Upload CSV';

  @override
  String get landingNavProduct => 'Product';

  @override
  String get landingNavWorkflow => 'Sequence';

  @override
  String get landingNavEvidence => 'Evidence';

  @override
  String get landingNavPricing => 'Prices';

  @override
  String get landingNavStart => 'Start Now';

  @override
  String get landingHeroEyebrow => 'AI Compliance Test from Rulefox';

  @override
  String get landingHeroCtaPrimary => 'Start AI Compliance Test';

  @override
  String get landingHeroCtaSecondary => 'View example proof';

  @override
  String get landingBenefit1Title => 'Invite employees';

  @override
  String get landingBenefit1Desc =>
      'Import via CSV or manually and assign tests in a structured manner.';

  @override
  String get landingBenefit2Title => 'Documenting AI Literacy';

  @override
  String get landingBenefit2Desc =>
      'Track progress, completion rates, and status centrally.';

  @override
  String get landingBenefit3Title => 'Export evidence';

  @override
  String get landingBenefit3Desc =>
      'Prepare reports for internal documentation, management, or audits.';

  @override
  String get landingFooterTagline =>
      'AI Compliance & Literacy Platform for Enterprise';

  @override
  String get footerImpressum => 'Impressum';

  @override
  String get footerDatenschutz => 'Privacy Policy';

  @override
  String get footerKontakt => 'Contact';

  @override
  String get navOverview => 'Overview';

  @override
  String get navEmployees => 'Employees';

  @override
  String get navTests => 'Tests';

  @override
  String get navEvidence => 'Evidence';

  @override
  String get navInvoice => 'Invoice';

  @override
  String get navSettings => 'Settings';

  @override
  String get dashboardTenantTitle => 'AI Compliance Dashboard';

  @override
  String get dashboardTenantSubtitle =>
      'Document AI literacy, test status and evidence centrally in Rulefox.';

  @override
  String get dashboardBannerTitle => 'AI Compliance in Focus';

  @override
  String get dashboardBannerDesc =>
      'Easily and clearly keep track of your employees\' test status, evidence, and AI literacy.';

  @override
  String get dashboardBannerCta => 'More about the EU AI Act';

  @override
  String get statEmployeesRecorded => 'Employees recorded';

  @override
  String get statEmployeesNoData => 'No employees added yet';

  @override
  String get statTestsAssigned => 'assigned tests';

  @override
  String get statTestsNoData => 'No tests assigned yet';

  @override
  String get statCompleted => 'Completed';

  @override
  String get statCompletionRate => 'Completion rate';

  @override
  String get statEvidenceAvailable => 'Evidence available';

  @override
  String get statEvidenceNoData => 'No evidence available yet';

  @override
  String get nextStepsTitle => 'Next Steps';

  @override
  String get step1Title => 'Complete company data';

  @override
  String get step1Desc => 'Add to your company information';

  @override
  String get step1Btn => 'Start';

  @override
  String get step2Title => 'Employees import';

  @override
  String get step2Desc => 'Upload your employees or add them manually.';

  @override
  String get step2Btn => 'Import';

  @override
  String get step3Title => 'Assign compliance test';

  @override
  String get step3Desc => 'Assign the AI compliance test to your employees';

  @override
  String get step3Btn => 'Assign test';

  @override
  String get step4Title => 'Export evidence';

  @override
  String get step4Desc => 'Export evidence for internal or external audits';

  @override
  String get step4Btn => 'Evidence';

  @override
  String get currentAllocationsTitle => 'Current allocations';

  @override
  String get showAll => 'Show all';

  @override
  String get noTestsAssigned => 'No tests assigned yet';

  @override
  String get noTestsAssignedDesc =>
      'Once you assign tests, you will see the status and progress of your employees here.';

  @override
  String get inviteEmployees => 'Invite employees';

  @override
  String get titleLanding => 'RuleFox – AI Compliance for Enterprise';

  @override
  String get titleLogin => 'Login · RuleFox';

  @override
  String get titleSignup => 'Registration · RuleFox';

  @override
  String get titleDashboard => 'AI Compliance Dashboard · RuleFox';

  @override
  String get titleAssessmentComplete => 'Assessment completed · RuleFox';

  @override
  String get titleOwnerDashboard => 'Owner Dashboard · RuleFox';

  @override
  String get titleOwnerTestManagement => 'Test Management · RuleFox';

  @override
  String get titleOwnerNewTest => 'New test · RuleFox';

  @override
  String get titleTenantDashboard => 'AI Compliance Dashboard · RuleFox';

  @override
  String get titleTenantAvailableTests => 'Available tests · RuleFox';

  @override
  String get titleTenantTestQuota => 'Test quota · RuleFox';

  @override
  String get titleAssignEmployees => 'Assign employees · RuleFox';

  @override
  String get titleEmployees => 'Employees · RuleFox';

  @override
  String get titleBilling => 'Billing · RuleFox';

  @override
  String get titlePurchaseHistory => 'Purchase history · RuleFox';

  @override
  String get titleInvoice => 'Invoice · RuleFox';

  @override
  String get titleCheckout => 'Checkout · RuleFox';

  @override
  String get titleAssessmentReady => 'Assessment ready · RuleFox';

  @override
  String get titleTestDetail => 'AI Compliance Test · RuleFox';

  @override
  String get titleAssessmentQuestions => 'AI Compliance Test · RuleFox';

  @override
  String get titleResults => 'Results · RuleFox';

  @override
  String get landingHeroStatEmployees => 'Employees';

  @override
  String get landingHeroStatCompleted => 'Completed';

  @override
  String get landingHeroBannerTitle => 'AI Compliance at a glance';

  @override
  String get landingHeroBannerDesc =>
      'Manage test status, employees and evidence centrally.';

  @override
  String get landingHeroDashboardTitle => 'AI Compliance Dashboard';

  @override
  String navQuota(Object count) {
    return 'Quota: $count tests';
  }

  @override
  String navCredits(Object count) {
    return '$count Credits';
  }

  @override
  String get navFooterTagline => 'Compliance that is verifiable.';

  @override
  String get navFooterLogoText => 'RULEFOX';

  @override
  String get screenTenantDashboard => 'AI Compliance Dashboard';

  @override
  String get screenEmployees => 'Employees';

  @override
  String get screenAvailableTests => 'Available tests';

  @override
  String get screenResults => 'Results';

  @override
  String get screenBilling => 'Billing';

  @override
  String get screenSettings => 'Settings';

  @override
  String get screenOwnerDashboard => 'Owner Dashboard';

  @override
  String get screenOwnerTestManagement => 'Test Management';

  @override
  String get subtitleTenantDashboard =>
      'Document AI literacy, test status, and evidence centrally in Rulefox.';

  @override
  String get subtitleEmployees =>
      'Manage and invite your employees to compliance tests.';

  @override
  String get subtitleAvailableTests =>
      'Find all available tests for your organization here.';

  @override
  String get subtitleResults =>
      'Review results and evidence of your employees.';

  @override
  String get subtitleBilling =>
      'Manage your subscriptions, invoices, and payment methods.';

  @override
  String get subtitleSettings =>
      'Configure your personal and company settings.';

  @override
  String get vatOptional => 'VAT (Optional)';

  @override
  String get tabOverview => 'Overview';

  @override
  String get tabInvoices => 'Invoices';

  @override
  String get labelBannerTitle => 'Quota & Billing';

  @override
  String get labelBannerSubtitle =>
      'Manage trial quotas, invoices, and payments for your business.';

  @override
  String get labelAvailableTests => 'Available credits';

  @override
  String get labelAssigned => 'Assigned';

  @override
  String get labelPaid => 'Paid';

  @override
  String get labelViewReceipt => 'View Receipt';

  @override
  String get labelLastPurchase => 'Last purchase';

  @override
  String get labelInvoices => 'Invoices';

  @override
  String get hintAiCompliance => 'AI Compliance';

  @override
  String get hintActiveInvites => 'Active invitations';

  @override
  String get labelAvailable => 'available';

  @override
  String get labelChoosePackage => 'Choose Package';

  @override
  String get labelCredits => 'Credits';

  @override
  String get labelEur => 'EUR';

  @override
  String get authManageCompliance => 'Manage AI compliance centrally.';

  @override
  String get authManageComplianceDesc =>
      'Rulefox guides companies from setup and employee invitation to exportable proof.';

  @override
  String get authCheckQuotas => 'Keeping an eye on test quotas and allocations';

  @override
  String get authCheckEvidence => 'Evidence-oriented results';

  @override
  String get authCheckInterface => 'Reduced, audit-compliant interface';

  @override
  String get authLoginDashboard => 'Login to the dashboard';

  @override
  String get authLoginDashboardDesc =>
      'Sign in to manage tests, staff, and evidence.';

  @override
  String get authEmailAddress => 'E-mail address';

  @override
  String get authEmailHint => 'admin@unternehmen.at';

  @override
  String get authCreateAccount => 'Create account';

  @override
  String get authReadyMinutes => 'Ready to go in minutes.';

  @override
  String get authReadyMinutesDesc =>
      'After registration, you can import employees, assign tests, and export evidence.';

  @override
  String get authStepCreateBusiness => 'Create a business';

  @override
  String get authStepSelectQuota => 'Select quota';

  @override
  String get authStepStartCompliance => 'Start AI Compliance Test';

  @override
  String get authSettingUpBusiness => 'Setting up a business';

  @override
  String get authSettingUpBusinessDesc =>
      'Create your Rulefox account and start the AI Compliance Test.';

  @override
  String get authFirstName => 'First name';

  @override
  String get authFirstNameHint => 'Max';

  @override
  String get authLastName => 'Last name';

  @override
  String get authLastNameHint => 'Mustermann';

  @override
  String get authEmail => 'E-mail';

  @override
  String get authEmailHintAlt => 'max@beispiel.at';

  @override
  String get authCompany => 'Company';

  @override
  String get authCompanyHint => 'Beispiel GmbH';

  @override
  String get authCountryLabel => 'Country';

  @override
  String get authSelectCountry => 'Select country';

  @override
  String get authCategory => 'Category';

  @override
  String get authSelectCategory => 'Select category';

  @override
  String get authVatOptional => 'VAT (optional)';

  @override
  String get authVatHint => 'Enter VAT number';

  @override
  String get authAddress => 'Address';

  @override
  String get authAddressHint => 'Enter your address';

  @override
  String get authUpdatePassword => 'Update password';

  @override
  String get authVerifyOtp => 'Verify OTP';

  @override
  String get buttonChoose => 'Choose';

  @override
  String get billingCreditsTaken => 'Credits Taken';

  @override
  String get billingTotalSpent => 'Total Spent';

  @override
  String get billingPendingInvoices => 'Pending Invoices';

  @override
  String get billingTotalThroughoutTime => 'Total throughout time';

  @override
  String get billingSuccessfulPayments => 'Successful payments';

  @override
  String get billingRequireAttention => 'Require attention';

  @override
  String get statEvidence => 'Evidence';

  @override
  String get statExportable => 'exportable';

  @override
  String get statAverage => 'Average';

  @override
  String get statOpen => 'Open';

  @override
  String get statInvitations => 'Invitations';

  @override
  String statAssignedOutOf(Object count, Object total) {
    return '$count of $total assigned';
  }

  @override
  String get exportEvidenceAction => 'Export evidence';

  @override
  String get testResultsTitle => 'Test results';

  @override
  String get exportCsvAction => 'Export CSV';

  @override
  String get filterAllStatus => 'All Status';

  @override
  String get filterAllDepartments => 'All Departments';

  @override
  String get statEmployees => 'Employees';

  @override
  String get statInvited => 'Invited';

  @override
  String get statCertificates => 'Certificates';

  @override
  String get tabEmployees => 'Employees';

  @override
  String get tabInvites => 'Invites';

  @override
  String get tabImport => 'Import';

  @override
  String get editEmployee => 'Edit Employee';

  @override
  String get labelOr => 'OR';

  @override
  String get labelUploadCsv => 'Upload CSV';

  @override
  String get labelTapChangeFile => 'Tap to change file';

  @override
  String get labelDragDropFile => 'Drag & drop your file here';

  @override
  String get labelBrowseFile => 'Browse File';

  @override
  String get labelDownloadTemplate => 'Download CSV Template';

  @override
  String get saveDetails => 'Save Details';

  @override
  String get addEmployees => 'Add Employees';

  @override
  String get labelDownload => 'Download';

  @override
  String get labelRemind => 'Remind';

  @override
  String get resultsColCompletion => 'Completion';

  @override
  String get resultsColProof => 'Proof';

  @override
  String get resultsStatTestResult => 'Test result';

  @override
  String get resultsPageTitle => 'Results & Evidence';

  @override
  String get resultsPageSubtitle =>
      'Document AI literacy, test status and evidence centrally in Rulefox.';

  @override
  String get snackNoResultsToExport => 'No passed results to export.';

  @override
  String get csvHeaderEmployee => 'Employee';

  @override
  String get csvHeaderTest => 'Test';

  @override
  String get csvHeaderScore => 'Score';

  @override
  String get csvHeaderStatus => 'Status';

  @override
  String get csvHeaderDate => 'Completion';

  @override
  String get labelEmployees => 'Employees';

  @override
  String get statusInvited => 'Invited';

  @override
  String get statusExpired => 'Expired';

  @override
  String get errorPassedOnly => 'Only available for passed tests.';

  @override
  String snackReminderSent(String name) {
    return 'Reminder sent to $name';
  }

  @override
  String get snackError => 'Error';

  @override
  String get filterNone => 'None';

  @override
  String get labelDepartment => 'Department';

  @override
  String get labelEmployeeID => 'Employee ID';

  @override
  String get filterDateNewest => 'Date Added (Newest)';

  @override
  String get filterDateOldest => 'Date Added (Oldest)';

  @override
  String get buttonAddEmployees => 'Add employees';

  @override
  String get labelFirstName => 'First Name';

  @override
  String get labelLastName => 'Last Name';

  @override
  String get labelEmail => 'Email';

  @override
  String get labelAction => 'Action';

  @override
  String get tooltipEdit => 'Edit Details';

  @override
  String get tooltipDelete => 'Delete';

  @override
  String get msgSaving => 'Saving...';

  @override
  String get msgEmployeeSaved => 'Employee saved successfully!';

  @override
  String get msgImporting => 'Importing Employees...';

  @override
  String get msgEmployeesImported => 'Employees imported successfully!';

  @override
  String get titleDeleteEmployee => 'Delete Employee';

  @override
  String msgDeleteConfirm(Object name) {
    return 'Are you sure you want to delete $name?\nThis action cannot be undone.';
  }

  @override
  String get labelCancel => 'Cancel';

  @override
  String get labelDelete => 'Delete';

  @override
  String get labelOthers => 'Others';

  @override
  String get ownerPlatformOverview => 'Rulefox platform overview';

  @override
  String get ownerPlatformDesc =>
      'Manage tests, tenants, and platform metrics in one place.';

  @override
  String get statRegisteredTests => 'Registered tests';

  @override
  String get statRegisteredTestsHint => 'Active test products';

  @override
  String get statActiveClients => 'Active clients';

  @override
  String get statActiveClientsHint => 'Pursue';

  @override
  String get statUsers => 'users';

  @override
  String get statUsersHint => 'Invited persons';

  @override
  String get statCompletionRateHint => 'Across all tests';

  @override
  String get titleCurrentTestProducts => 'Current test products';

  @override
  String get actionShowAll => 'Show all';

  @override
  String get columnTest => 'test';

  @override
  String get columnStatus => 'Status';

  @override
  String get columnPrice => 'Price';

  @override
  String get columnAction => 'Action';

  @override
  String get titleNextAdminSteps => 'Next admin steps';

  @override
  String get stepComplianceCheckTitle => 'AI Compliance Test Check';

  @override
  String get stepComplianceCheckDesc =>
      'Questions, prices and supporting documents';

  @override
  String get stepClientOnboardingTitle => 'Client onboarding';

  @override
  String get stepClientOnboardingDesc => 'Prepare demo client';

  @override
  String get buttonOpen => 'Open';

  @override
  String get buttonStart => 'Start';

  @override
  String get buttonPlan => 'Plan';

  @override
  String get titleTestManagement => 'Test Management';

  @override
  String get descTestManagement =>
      'Manage test products, prices, and release status.';

  @override
  String get titleTestOverview => 'Test overview';

  @override
  String get columnName => 'name';

  @override
  String get columnQuestions => 'Questions';

  @override
  String get columnLastUpdated => 'Last updated';

  @override
  String get titleCreateNewTest => 'Create new test';

  @override
  String get subtitleCreateNewTest => 'Prepare a test product as a draft.';

  @override
  String get labelTestName => 'Test name';

  @override
  String get labelBriefDescription => 'Brief description';

  @override
  String get labelLanguage => 'Language';

  @override
  String get tooltipCannotDownloadFailed =>
      'Certificate is only available for passed tests.';

  @override
  String get buttonBuyQuota => 'Buy quota';

  @override
  String get buttonBuyMoreTests => 'Buy more tests';

  @override
  String get buttonBuyTest => 'Buy test';

  @override
  String get buttonNotifyMe => 'Notify me';

  @override
  String get labelBought => 'Bought';

  @override
  String get labelAssignedCount => 'Assigned';

  @override
  String get labelAvailableCount => 'Available';

  @override
  String get labelSoon => 'Soon';

  @override
  String get labelActive => 'Active';

  @override
  String get labelPurchaseHistory => 'Purchase history';

  @override
  String get labelPerPerson => 'per person';

  @override
  String get labelTestQuota => 'Test Quota';

  @override
  String get labelPurchasedTests => 'Purchased tests';

  @override
  String get howItWorksTitle => 'How the assignment works';

  @override
  String get howItWorksStep1Title => 'Buy quota';

  @override
  String get howItWorksStep1Desc => 'Select the number of tests required.';

  @override
  String get howItWorksStep2Title => 'Select employees';

  @override
  String get howItWorksStep2Desc => 'Assign the test to individuals or groups.';

  @override
  String get howItWorksStep3Title => 'Export evidence';

  @override
  String get howItWorksStep3Desc =>
      'Results can be documented upon completion.';

  @override
  String get dropdownAvailableTests => 'Available tests';

  @override
  String get dropdownPurchasedTests => 'Purchased tests';

  @override
  String bannerQuotaDesc(int n) {
    return 'You have purchased $n tests. Assign any unused tests to your employees.';
  }

  @override
  String get labelSortByName => 'Sort by Name';

  @override
  String get labelSortByCredits => 'Sort by Credits';

  @override
  String get labelAllCategories => 'All Categories';

  @override
  String get categorySecurity => 'Security';

  @override
  String get categoryCompliance => 'Compliance';

  @override
  String get labelAssign => 'Assign';

  @override
  String get categoryDevOps => 'DevOps';

  @override
  String get labelConfirmation => 'Confirmation';

  @override
  String get labelTest => 'Test:';

  @override
  String get labelTotalSeats => 'Total Seats:';

  @override
  String get labelRemainingSeats => 'Remaining Seats:';

  @override
  String get labelSelectedEmployees => 'Selected Employees:';

  @override
  String get labelStartingDate => 'Starting Date:';

  @override
  String get labelTestExpiry => 'Test Expiry:';

  @override
  String get buttonConfirm => 'Confirm';

  @override
  String get labelAllDepartments => 'All departments';

  @override
  String get labelAllStatuses => 'All statuses';

  @override
  String get bannerAssignTitle => 'Assign AI Compliance Test';

  @override
  String bannerAssignDesc(int count) {
    return 'Select the employees who should take the test. Available tests: $count.';
  }

  @override
  String get buttonInviteSelected => 'Invite selected';

  @override
  String get errorSelectAtLeastOne => 'Please select at least one employee.';

  @override
  String errorInsufficientSeats(int count) {
    return 'Insufficient seats. You only have $count seats available.';
  }

  @override
  String get columnEmployeeId => 'Employee ID';

  @override
  String get columnFirstName => 'First Name';

  @override
  String get columnLastName => 'Last Name';

  @override
  String get columnEmail => 'Email';

  @override
  String get columnDepartment => 'Department';

  @override
  String get labelReassign => 'Re-assign';

  @override
  String get subtitleAssignEmployees =>
      'Document AI literacy, test status and evidence centrally in Rulefox.';

  @override
  String get labelEdit => 'Edit';

  @override
  String get labelSaveAsDraft => 'Save as Draft';

  @override
  String get labelUploadAndPublish => 'Upload & Publish';

  @override
  String get labelPreviewAndPublish => 'Preview & Publish';

  @override
  String get labelUploadTestFile => 'Upload Test File (.json)';

  @override
  String get labelTimeLimitMinutes => 'Time Limit (Minutes)';

  @override
  String get labelTimeLimitHint => 'e.g. 20 (0 for no limit)';

  @override
  String get labelCreditsRequired => 'Credits Required';

  @override
  String get labelCreditsHint => 'e.g. 30';

  @override
  String get labelFreeTest => 'Free Test';

  @override
  String get labelNoCreditsRequired => 'No credits required';

  @override
  String get labelRequiresCredits => 'Requires credits to purchase';

  @override
  String get labelTapToChangeFile => 'Tap to change file';

  @override
  String get subtitleOwnerDashboard =>
      'Manage the platform, test products, and clients centrally.';

  @override
  String get labelMore => 'more';

  @override
  String get searchTests => 'Search tests';

  @override
  String get assessmentVerifying => 'Verifying your invitation...';

  @override
  String get assessmentInvalidToken => 'Invalid or missing token.';

  @override
  String get assessmentVerificationFailed => 'Verification failed.';

  @override
  String get assessmentVerificationError =>
      'An error occurred during verification. Please try again later.';

  @override
  String get assessmentAlreadyCompleted => 'Assessment Already Completed';

  @override
  String get assessmentInvalidLink => 'Invalid or Expired Link';

  @override
  String get assessmentAlreadySubmittedDesc =>
      'You have already submitted this assessment. If you believe this is an error, please contact your administrator.';

  @override
  String get assessmentExpiredLinkDesc =>
      'This invitation link has expired or is invalid. Please request a new link from your administrator to take the assessment.';

  @override
  String get assessmentCloseButton => 'Close';

  @override
  String get assessmentStartTestBtn => 'Start test';

  @override
  String get assessmentResumeTestBtn => 'Resume test';

  @override
  String get assessmentLoadingDetails => 'Loading Test Details...';

  @override
  String get testRunnerPublishing => 'Publishing...';

  @override
  String get testRunnerSubmitting => 'Submitting Test...';

  @override
  String get testRunnerPublishFailed => 'Publish failed. Please try again.';

  @override
  String get testRunnerSubmitFailed => 'Submit failed. Please try again.';

  @override
  String testRunnerFlaggedToReview(int count) {
    return 'You have $count flagged question(s). Please review before submitting.';
  }

  @override
  String get testRunnerReviewFlaggedQuestions => 'Review Flagged Questions';

  @override
  String testRunnerReviewingFlagged(int current, int total) {
    return 'Reviewing Flagged: $current of $total';
  }

  @override
  String get testRunnerPreviousFlag => 'Previous Flag';

  @override
  String get testRunnerNextFlag => 'Next Flag';

  @override
  String get testRunnerExitReview => 'Exit Review';

  @override
  String get testRunnerFinishReview => 'Finish Review';

  @override
  String get testRunnerNotStarted => 'Not started';

  @override
  String get testRunnerInProgress => 'In Progress';

  @override
  String testRunnerApproxMinutes(int minutes) {
    return 'approximately $minutes minutes';
  }

  @override
  String get testRunnerClosePreview => 'Close Preview';

  @override
  String get testRunnerPreviewTest => 'Preview Test';

  @override
  String get testRunnerStartWithTest => 'Start with test';

  @override
  String get testRunnerSectionPassed => 'Passed';

  @override
  String get testRunnerSectionFailed => 'Failed';

  @override
  String get testRunnerExitPortal => 'Exit Portal';

  @override
  String get testRunnerIntegrityCheck =>
      'Integrity check - please stay in full-screen mode.';

  @override
  String get testRunnerReenterFullscreen => 'Re-enter fullscreen';

  @override
  String get testRunnerExitAssessmentTitle => 'Exit Assessment?';

  @override
  String get testRunnerExitAssessmentDesc =>
      'Are you sure you want to exit? Your progress is saved but the timer will continue.';

  @override
  String get testRunnerStay => 'Stay';

  @override
  String get testRunnerExit => 'Exit';

  @override
  String testRunnerReviewCount(int count) {
    return 'Review ($count)';
  }

  @override
  String get testRunnerTimesUp => 'Time\'s Up!';

  @override
  String testRunnerSubmitCountdown(int countdown) {
    return 'Your assessment is being submitted in $countdown...';
  }

  @override
  String get testRunnerPreviewModeLabel => 'Preview Mode';

  @override
  String testRunnerQuestionAnsweredOfTotal(int answered, int total) {
    return '$answered of $total questions answered';
  }

  @override
  String assessmentDescriptionDefault(String testName) {
    return 'You have been invited to take the $testName. This assessment evaluates your knowledge and skills in this specific area.';
  }

  @override
  String get certVerificationCertificate => 'Verification Certificate';

  @override
  String get certPassedVerified => 'PASSED & VERIFIED';

  @override
  String get certThisIsToCertify => 'THIS IS TO CERTIFY THAT';

  @override
  String get certAcmeEmployee =>
      'Marketing Operations Specialist • Acme Enterprise GmbH';

  @override
  String get certAssessmentTest => 'Assessment Test';

  @override
  String get certDateOfCompletion => 'Date of Completion';

  @override
  String get certScoreAchieved => 'Score Achieved';

  @override
  String get certComplianceBoard => 'Rulefox Compliance Board';

  @override
  String get certVerifiedDigitally => 'Verified Digitally';

  @override
  String get labelSummary => 'Summary';

  @override
  String get labelVAT => 'VAT';

  @override
  String get labelInTotal => 'In total';

  @override
  String get labelProcessingPayment => 'Processing Payment...';

  @override
  String get labelCalculating => 'Calculating...';

  @override
  String get labelSecurePayment => 'Secure payment';

  @override
  String get labelPaymentDetails => 'Payment details';

  @override
  String get labelCardholder => 'Cardholder';

  @override
  String get labelCardNumber => 'Card number';

  @override
  String get labelBillingAddress => 'Billing address';

  @override
  String get labelBuyNow => 'Buy now';

  @override
  String get labelEmailForInvoice => 'Email for invoice';

  @override
  String get hintBillingEmail => 'billing@beispiel.at';

  @override
  String get hintFullName => 'Full name';

  @override
  String get hintBillingAddress => 'Musterstraße 1, 1010 Wien';

  @override
  String get msgPaymentCanceled => 'Payment was canceled';

  @override
  String get msgPaymentFailed => 'Payment failed. Please try again.';

  @override
  String get msgPaymentFailedMethod =>
      'Payment failed. Please try a different payment method.';

  @override
  String get msgPaymentProcessingError =>
      'Payment processing error. Please try again.';

  @override
  String get msgEnterCompleteCard => 'Please enter complete card information';

  @override
  String get msgEnterEmailReceipt => 'Please enter your email for the receipt';

  @override
  String msgCreditsAdded(int count, double total) {
    return '$count credits added to your account. Total paid: €$total';
  }

  @override
  String get labelAiComplianceCredits => 'AI Compliance Credits';

  @override
  String labelCreditsXPrice(int count, String price) {
    return '$count credits x €$price';
  }

  @override
  String get labelByCountryInvoicing => 'by country of invoicing';

  @override
  String labelUseBookkeepingEmail(String email) {
    return 'Use bookkeeping email: $email';
  }

  @override
  String labelUseAccountEmail(String email) {
    return 'Use account email: $email';
  }

  @override
  String get labelPopularBadge => 'POPULAR';

  @override
  String get labelActionColumn => 'ACTION';

  @override
  String get labelCreditsUnit => 'Credits';

  @override
  String get pkgDescSmall => 'For small teams and pilot phase.';

  @override
  String get pkgDescMedium => 'Recommended for departments.';

  @override
  String get pkgDescLarge => 'For larger rollouts.';

  @override
  String get labelNoTestsAvailable => 'No tests available';

  @override
  String get labelBillingPageTitle => 'Billing & Credits';

  @override
  String get screenCheckout => 'Checkout';

  @override
  String get certSecureDigitalProof => 'SECURE DIGITAL PROOF';

  @override
  String get certCloseButton => 'Close';

  @override
  String get certViewPdf => 'View PDF Certificate';

  @override
  String get certReturnHome => 'Return Home';

  @override
  String get titleTestHistory => 'Test History';

  @override
  String get buttonAddNewVersion => 'Add New Version';

  @override
  String get columnVersions => 'Versions';

  @override
  String get emptyNoVersions => 'No versions found';

  @override
  String get labelPrimary => 'Primary';

  @override
  String get buttonMakePrimary => 'Make Primary';

  @override
  String get buttonPreview => 'Preview';

  @override
  String get msgUpdatingPrimaryVersion => 'Updating Primary Version...';

  @override
  String get msgPrimaryVersionUpdated => 'Primary Version Updated!';

  @override
  String get msgPreparingPreview => 'Preparing Preview...';

  @override
  String get msgNoTestData => 'No test data found for this version.';

  @override
  String get msgPublishingTest => 'Publishing Test...';

  @override
  String get msgSavingDraft => 'Saving Draft...';

  @override
  String get msgNewVersionDraft => 'New Version Uploaded as Draft!';

  @override
  String get msgTestSavedDraft => 'Test Saved as Draft!';

  @override
  String get titleUpdateTest => 'Update Test';

  @override
  String get msgActionFailed => 'Action Failed';

  @override
  String get msgSessionExpired => 'Session expired. Please log in again.';

  @override
  String get msgInvalidTestFile => 'Invalid test file structure';

  @override
  String get msgCouldNotReadFile => 'Could not read file. Try again.';

  @override
  String get errorUploadJson => 'Please upload a JSON test file';

  @override
  String get errorTestNameRequired => 'Test name is required';

  @override
  String get errorCreditsRequired => 'Credits required';

  @override
  String get errorValidNumber => 'Enter a valid number';

  @override
  String get errorSelectCategory => 'Please select a category';

  @override
  String get errorTimeLimitNegative =>
      'Time limit cannot be negative (0 for no limit)';

  @override
  String get errorTimeLimitInvalid =>
      'Enter a valid number or leave empty for no limit';

  @override
  String get labelVersionNumberAuto => 'Version Number (Auto-generated)';

  @override
  String get hintTestName => 'e.g. AI Compliance Test';

  @override
  String get errorInvalidJsonFile =>
      'Invalid JSON file. Please check the content.';

  @override
  String get errorInvalidJsonStructure => 'Invalid JSON file structure';

  @override
  String get labelSwitchToVisualBuilder => 'Switch to Visual Builder';

  @override
  String get labelSwitchToJsonUpload => 'Switch to JSON Upload';

  @override
  String get labelTestBuiltSuccessfully => 'Test Built Successfully';

  @override
  String get labelEditInVisualBuilder => 'Edit in Visual Builder';

  @override
  String get labelEditTestQuestions => 'Edit Test Questions';

  @override
  String get labelBuildTestVisually => 'Build Test Visually';

  @override
  String get labelBuildTestDescription =>
      'Add sections and questions to structure your test';

  @override
  String get labelPassingScore => 'Passing Score (%)';

  @override
  String get labelAddSection => 'Add Section';

  @override
  String get labelAddQuestion => 'Add Question';

  @override
  String get labelAddOption => 'Add Option';

  @override
  String get questionTypePickerTitle => 'Choose Question Type';

  @override
  String get questionTypePickerSubtitle =>
      'Select how you want the question to be answered';

  @override
  String get questionTypeMultipleChoice => 'Multiple Choice';

  @override
  String get questionTypeMultipleChoiceDesc =>
      'Provide options and let users pick the correct one(s)';

  @override
  String get questionTypeTextInput => 'Text Input';

  @override
  String get questionTypeTextInputDesc =>
      'Users type their answer in a free text field';

  @override
  String get labelQuestion => 'Question';

  @override
  String get labelOptionsInstruction =>
      'OPTIONS • TAP CIRCLE TO MARK CORRECT ANSWER';

  @override
  String get labelSaveTest => 'Save Test';

  @override
  String get errorAddOneSection => 'Add at least one section.';

  @override
  String get errorInvalidScore =>
      'Passing score must be a number between 0 and 100.';

  @override
  String labelSectionCount(int num) {
    return 'Section $num';
  }

  @override
  String labelQuestionCount(int num) {
    return 'Question $num';
  }

  @override
  String labelOptionPrefix(String key) {
    return 'Option $key...';
  }

  @override
  String get labelSectionTitleHint => 'Section title...';

  @override
  String get labelQuestionHint => 'Enter question text...';

  @override
  String errorSectionTitleEmptyDetailed(int num) {
    return 'Section $num title cannot be empty.';
  }

  @override
  String errorQuestionEmptyDetailed(int qNum, String sTitle) {
    return 'Question $qNum in \"$sTitle\" cannot be empty.';
  }

  @override
  String errorOptionEmptyDetailed(String key, int qNum, String sTitle) {
    return 'Option $key of question $qNum in \"$sTitle\" cannot be empty.';
  }

  @override
  String errorCorrectAnswerDetailed(int qNum, String sTitle) {
    return 'Please select a correct answer for question $qNum in \"$sTitle\".';
  }

  @override
  String labelSectionsAndQuestions(
    int sCount,
    String sPlural,
    int qCount,
    String qPlural,
  ) {
    return '$sCount section$sPlural • $qCount question$qPlural';
  }

  @override
  String get labelChooseAddQuestions => 'Choose How to Add Questions';

  @override
  String get labelUploadJson => 'Upload JSON';

  @override
  String get labelImportTestFile => 'Import a pre-made test file';

  @override
  String get labelBuildVisually => 'Build Visually';

  @override
  String get labelCreateQuestionsInside => 'Create questions inside the app';

  @override
  String get testEditorTypeImageUpload => 'Image Upload';

  @override
  String get testEditorTypeImageUploadDesc =>
      'Attach an image for visual question context';

  @override
  String get testEditorReplaceImage => 'Replace Image';

  @override
  String get testEditorUploading => 'Uploading...';

  @override
  String get testEditorTapToAttachImage => 'Tap to attach an image';

  @override
  String get testEditorImageSupportedFormats => 'PNG, JPG, WEBP supported';

  @override
  String get testEditorCorrectAnswerForGrading =>
      'CORRECT ANSWER FOR AUTOMATIC GRADING';

  @override
  String get testEditorEnterCorrectAnswer => 'Enter correct answer';

  @override
  String get testRunnerTypeAnswerHere => 'Type your answer here...';

  @override
  String get landingV2HeroTitle =>
      'Make compliance knowledge measurable. Document evidence centrally.';

  @override
  String get landingV2HeroDesc =>
      'RuleFox allows companies to test whether employees understand key compliance requirements – and provides exportable evidence for internal documentation, management and audits.';

  @override
  String get landingV2HeroBtnStart => 'Start EU AI Compliance Test';

  @override
  String get landingV2HeroBtnEvidence => 'View example proof';

  @override
  String get landingV2HeroNote1 => 'Currently\navailable:';

  @override
  String get landingV2HeroNote2 => 'EU AI\nCompliance\nTest.';

  @override
  String get landingV2HeroNote3 => 'Further compliance tests\nwill follow.';

  @override
  String get landingV2FloatTestTitle => 'Test';

  @override
  String get landingV2FloatTestDesc => 'Verify knowledge';

  @override
  String get landingV2FloatEvalTitle => 'Evaluate';

  @override
  String get landingV2FloatEvalDesc => 'Make progress visible';

  @override
  String get landingV2FloatProveTitle => 'Prove';

  @override
  String get landingV2FloatProveDesc => 'Export evidence';

  @override
  String get landingV2FloatSecureTitle => 'Be secure';

  @override
  String get landingV2FloatSecureDesc => 'Audit-ready and traceable';

  @override
  String get landingV2TestsEyebrow => 'Available tests';

  @override
  String get landingV2TestsTitle => 'Start with the first available test.';

  @override
  String get landingV2TestsDesc =>
      'RuleFox has a modular structure. The EU AI Compliance Test is the first available test. Further compliance topics can be tested, evaluated, and documented via the same platform in the future.';

  @override
  String get landingV2Test1Eyebrow => 'FIRST AVAILABLE TEST';

  @override
  String get landingV2Test1Desc =>
      'Check whether employees understand the most important basics for the safe and responsible use of AI systems – including relevant duties, risk awareness and practical application in everyday work.';

  @override
  String get landingV2Test1Meta1 => '21 questions';

  @override
  String get landingV2Test1Meta2 => 'approx. 15 min.';

  @override
  String get landingV2Test1Meta3 => 'DE & EN';

  @override
  String get landingV2PriceAmount => '€99';

  @override
  String get landingV2PriceUnit => 'per test';

  @override
  String get landingV2TestSoonTitle => 'Further compliance tests';

  @override
  String get landingV2TestSoonBadge => 'Soon';

  @override
  String get landingV2TestSoonDesc =>
      'RuleFox is continuously being expanded with new test modules – for further compliance, training and verification obligations via a central platform.';

  @override
  String get landingV2TestSoonBtn => 'Available soon';

  @override
  String get landingV2TestsFooter =>
      'Do you need a specific compliance test for your company? Contact us — we are happy to review your individual topic requests.';

  @override
  String get landingV2PlatformEyebrow => 'Platform';

  @override
  String get landingV2PlatformTitle => 'One platform. Many compliance tests.';

  @override
  String get landingV2PlatformDesc =>
      'Whether it\'s AI compliance, data protection, security awareness or internal guidelines: RuleFox makes knowledge testable, results visible and evidence exportable.';

  @override
  String get landingV2PlatformCol1Title => 'Invite employees';

  @override
  String get landingV2PlatformCol1Desc =>
      'Add teams via CSV or invitation link and assign tests to specific tasks.';

  @override
  String get landingV2PlatformCol2Title => 'Evaluate progress';

  @override
  String get landingV2PlatformCol2Desc =>
      'Keep a central eye on participation rate, completion rate, pass rate and open invitations.';

  @override
  String get landingV2PlatformCol3Title => 'Export evidence';

  @override
  String get landingV2PlatformCol3Desc =>
      'Create individual reports and overall reports for documentation, management and audits.';

  @override
  String get landingV2ReportingEyebrow => 'Reporting & Insights';

  @override
  String get landingV2ReportingTitle => 'Make compliance progress visible.';

  @override
  String get landingV2ReportingDesc =>
      'RuleFox shows not only individual test results, but the entire progress of your company at a glance.';

  @override
  String get landingV2ReportingKpi1 => 'Participation rate';

  @override
  String get landingV2ReportingKpi1Sub => '156 of 200 employees invited';

  @override
  String get landingV2ReportingKpi2 => 'Completion rate';

  @override
  String get landingV2ReportingKpi2Sub => '97 of 156 tests completed';

  @override
  String get landingV2ReportingKpi3 => 'Pass rate';

  @override
  String get landingV2ReportingKpi3Sub => '82 of 97 tests passed';

  @override
  String get landingV2ReportingKpi4 => 'Average result';

  @override
  String get landingV2ReportingKpi4Sub => 'Average score of all participants';

  @override
  String get landingV2ReportingKpi5 => 'Open invitations';

  @override
  String get landingV2ReportingKpi5Sub => 'Employees have not yet started.';

  @override
  String get landingV2ReportingFeat1Title => 'Filter by departments';

  @override
  String get landingV2ReportingFeat1Desc =>
      'Compare progress by teams & departments.';

  @override
  String get landingV2ReportingFeat2Title => 'Keep track of progress';

  @override
  String get landingV2ReportingFeat2Desc =>
      'Analyze rollout development over time periods.';

  @override
  String get landingV2ReportingFeat3Title => 'Identify need for action';

  @override
  String get landingV2ReportingFeat3Desc =>
      'Quickly identify open tests and low results.';

  @override
  String get landingV2ReportingFeat4Title => 'Export & Reporting';

  @override
  String get landingV2ReportingFeat4Desc => 'Export reports as PDF or CSV.';

  @override
  String get landingV2SequenceEyebrow => 'Here\'s how it works';

  @override
  String get landingV2SequenceTitle =>
      'Three steps to documented compliance proof.';

  @override
  String get landingV2SequenceStep1Title => 'Invite employees';

  @override
  String get landingV2SequenceStep1Desc =>
      'Invite teams via CSV import or invitation link and assign the appropriate test.';

  @override
  String get landingV2SequenceStep2Title => 'Take the test';

  @override
  String get landingV2SequenceStep2Desc =>
      'Employees answer practical questions on the selected compliance topic in just a few minutes. The evaluation is automatic and transparent.';

  @override
  String get landingV2SequenceStep3Title => 'Export evidence';

  @override
  String get landingV2SequenceStep3Desc =>
      'Export individual certificates and an overall report as a PDF - ready for documentation, management, or audits.';

  @override
  String get landingV2EvidenceEyebrow => 'Evidence';

  @override
  String get landingV2EvidenceTitle => 'Don\'t just test. Prove it.';

  @override
  String get landingV2EvidenceDesc =>
      'Compliance is only valuable if it can be documented. RuleFox creates clear evidence of participation, results, and status—clearly organized, exportable, and internally traceable.';

  @override
  String get landingV2EvidenceFeat1Title => 'Individual proof per employee';

  @override
  String get landingV2EvidenceFeat1Desc =>
      'Name, test, date and result on one compact PDF.';

  @override
  String get landingV2EvidenceFeat2Title => 'Unique verification ID';

  @override
  String get landingV2EvidenceFeat2Desc =>
      'Each piece of evidence receives a unique reference for internal documentation and later allocation.';

  @override
  String get landingV2EvidenceFeat3Title => 'Overall report for management';

  @override
  String get landingV2EvidenceFeat3Desc =>
      'Overview of participation rate, status and progress of all tested employees in one report.';

  @override
  String get landingV2PricesEyebrow => 'Prices';

  @override
  String get landingV2PricesTitle => 'Transparent.\n€99 per test.';

  @override
  String get landingV2PricesDesc =>
      'Book individual tests or flexible quotas and use them for your employees as needed.';

  @override
  String get landingV2PricesFeat1 => '21 practical questions';

  @override
  String get landingV2PricesFeat2 => 'Processing time approximately 15 minutes';

  @override
  String get landingV2PricesFeat3 => 'German English';

  @override
  String get landingV2PricesFeat4 => 'automatic evaluation';

  @override
  String get landingV2PricesFeat5 => 'Individual proof as a PDF';

  @override
  String get landingV2PricesFeat6 => 'Reporting overview for the tenant';

  @override
  String get landingV2PricesBtnStart => 'Start test';

  @override
  String get landingV2PricesNote =>
      'All prices exclude VAT. Larger quantities and individual requirements available upon request.';

  @override
  String get landingV2ModalTitle => 'Example proof';

  @override
  String get landingV2ModalDesc =>
      'This is what the individual certificate looks like, which every employee receives after a successful test.';

  @override
  String get landingV2ModalBtnClose => 'Close';

  @override
  String get landingV2ModalBtnStart => 'Test it yourself now';

  @override
  String get landingV2MockDate => 'May 14, 2024';

  @override
  String get landingV2MockScore => '86% – passed';
}
